services:
  database:
    container_name: jobs_database
    image: postgres:17
    env_file:
      - .env
    profiles:
      - app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 4

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint: sh -c "chmod +x ./ops/entrypoint.sh && ./ops/entrypoint.sh"
    profiles:
      - app
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=jobs_database
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DEVISE_JWT_SECRET_KEY=${DEVISE_JWT_SECRET_KEY:-development}
    volumes:
      - ./api:/rails
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    profiles:
      - app
    environment:
      - HOST=0.0.0.0
      - NITRO_HOST=0.0.0.0
      - NUXT_API_SECRET=http://api:3000
      - NUXT_PUBLIC_API_BASE=http://localhost:3000
    ports:
      - "3001:3000"
    depends_on:
      - api

  swagger:
    image: swaggerapi/swagger-ui
    profiles:
      - docs
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./doc/openapi.yaml:/openapi.yaml

volumes:
  data:

networks:
  default:
    name: jobs
